image: node

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - mkdir .public
    - cp -r * .public
    - cp build/index.html build/404.html
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master